import Providers from './Provider'
import './globals.css'
import { Ubuntu } from 'next/font/google'

const inter = Ubuntu({ subsets: ['cyrillic'], weight : '400'})

export const metadata = {
  title: 'Pegion | The Messenger',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='light' style={{colorScheme : 'light'}}>

      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
        </body>
    </html>
  )
}
